import React, { useId, forwardRef } from 'react';

interface AutoInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helperText?: string;
  autoId?: boolean; // Génère automatiquement id/name si true (par défaut)
}

export const AutoInput = forwardRef<HTMLInputElement, AutoInputProps>(
  ({ label, error, helperText, autoId = true, id, name, className, ...props }, ref) => {
    const autoGeneratedId = useId();
    
    // Utilise id fourni ou génère automatiquement si autoId=true
    const inputId = id || (autoId ? `input-${autoGeneratedId}` : undefined);
    const inputName = name || (autoId ? inputId : undefined);
    
    const baseInputClasses = `
      w-full px-3 py-2 border rounded-lg transition-colors
      focus:outline-none focus:ring-2 focus:ring-blue-500/20
      disabled:opacity-50 disabled:cursor-not-allowed
    `;
    
    const errorClasses = error 
      ? 'border-red-500 focus:border-red-500 focus:ring-red-500/20'
      : 'border-gray-300 focus:border-blue-500';
    
    const finalClassName = `${baseInputClasses} ${errorClasses} ${className || ''}`.trim();
    
    if (label) {
      return (
        <div className="space-y-1">
          <label 
            htmlFor={inputId}
            className="block text-sm font-medium text-gray-700 dark:text-gray-300"
          >
            {label}
          </label>
          <input
            ref={ref}
            id={inputId}
            name={inputName}
            className={finalClassName}
            aria-describedby={
              error ? `${inputId}-error` : 
              helperText ? `${inputId}-helper` : undefined
            }
            aria-invalid={!!error}
            {...props}
          />
          {error && (
            <p id={`${inputId}-error`} className="text-sm text-red-600 dark:text-red-400">
              {error}
            </p>
          )}
          {helperText && !error && (
            <p id={`${inputId}-helper`} className="text-sm text-gray-500 dark:text-gray-400">
              {helperText}
            </p>
          )}
        </div>
      );
    }
    
    // Input sans label mais avec id/name automatiques
    return (
      <input
        ref={ref}
        id={inputId}
        name={inputName}
        className={finalClassName}
        aria-invalid={!!error}
        {...props}
      />
    );
  }
);

AutoInput.displayName = 'AutoInput';